// ==================== CONFIGURATION ====================
const SPREADSHEET_ID = 'YOUR_SPREADSHEET_ID'; // 👈 Apni sheet ID yahan dalen
const IMPORT_SHEET_PREFIX = 'Import_';

// ==================== WEB APP ====================
function doGet(e) {
  return HtmlService.createTemplateFromFile('Index')
    .evaluate()
    .setTitle('ERP Data Viewer')
    .setFaviconUrl('https://img.icons8.com/color/48/000000/search.png')
    .addMetaTag('viewport', 'width=device-width, initial-scale=1, shrink-to-fit=no');
}

// ==================== SETTINGS (ScriptProperties) ====================
function getSettings() {
  const sp = PropertiesService.getScriptProperties();
  const json = sp.getProperty('VIEWER_SETTINGS');
  if (json) return JSON.parse(json);
  return createDefaultSettings();
}

function createDefaultSettings() {
  const defaults = {
    schoolName: 'School ERP Data Viewer',
    logoUrl: 'https://img.icons8.com/color/96/000000/school.png',
    primaryColor: '#1a237e',
    theme: 'light',
    customFooterLine: 'Generated by School ERP Viewer',
    contactEmail: ''
  };
  PropertiesService.getScriptProperties().setProperty('VIEWER_SETTINGS', JSON.stringify(defaults));
  return defaults;
}

function updateSettings(settingsObj) {
  const current = getSettings();
  const merged = { ...current, ...settingsObj };
  PropertiesService.getScriptProperties().setProperty('VIEWER_SETTINGS', JSON.stringify(merged));
  return { success: true };
}

function resetSettings() {
  PropertiesService.getScriptProperties().deleteProperty('VIEWER_SETTINGS');
  return createDefaultSettings();
}

function clearCache() {
  PropertiesService.getScriptProperties().deleteAllProperties();
  return { success: true, message: 'Cache cleared' };
}

// ==================== DUMMY DATA ====================
function loadDummyData() {
  const csv = 
`=== Students ===
StudentID,GRNo,FullName,FatherName,Gender,DOB,Class,Section,Fee,Phone
STU-001,GR-2025-001,Ahmed Khan,Muhammad Khan,Male,2015-03-15,Class 4,A,5000,0300-1111111
STU-002,GR-2025-002,Fatima Ali,Ali Raza,Female,2012-07-22,Class 7,B,6000,0300-2222222

=== Teachers ===
TeacherID,EmpCode,Name,Qualification,Subjects,MonthlyPackage
TCH-001,EMP-001,Prof. Abdul Qadir,M.Sc Mathematics,Mathematics,75000

=== FeeHistory ===
StudentID,Date,Amount,Month,ReceiptNo
STU-001,2025-01-15,5000,2025-01,RCP-001

=== ExamRegistrations ===
RegistrationID,StudentID,StudentName,Class,ExamType,ExamYear,Subjects,FeeStatus
EXR-001,STU-001,Ahmed Khan,Class 4,Annual Examination,2025,English;Math,Cleared`;
  return importCSVData(csv);
}

// ==================== CSV IMPORT ====================
function importCSVData(csvContent) {
  const lock = LockService.getScriptLock(); lock.waitLock(10000);
  try {
    const doc = SpreadsheetApp.openById(SPREADSHEET_ID);
    // Delete old import sheets
    doc.getSheets().forEach(sh => {
      if (sh.getName().startsWith(IMPORT_SHEET_PREFIX)) doc.deleteSheet(sh);
    });
    const sections = csvContent.split(/=== (.+?) ===/g).filter(Boolean);
    const imported = [];
    for (let i = 0; i < sections.length; i += 2) {
      const sheetName = IMPORT_SHEET_PREFIX + sections[i].trim();
      const csvPart = sections[i+1].trim();
      if (!csvPart) continue;
      const rows = Utilities.parseCsv(csvPart);
      if (rows.length === 0) continue;
      let sheet = doc.getSheetByName(sheetName);
      if (!sheet) sheet = doc.insertSheet(sheetName);
      else sheet.clear();
      sheet.getRange(1, 1, rows.length, rows[0].length).setValues(rows);
      imported.push({ name: sheetName, displayName: sections[i].trim(), rowCount: rows.length - 1 });
    }
    return { success: true, imported };
  } catch(e) {
    return { success: false, message: e.toString() };
  } finally {
    lock.releaseLock();
  }
}

function getImportedSheets() {
  const doc = SpreadsheetApp.openById(SPREADSHEET_ID);
  return doc.getSheets()
    .filter(sh => sh.getName().startsWith(IMPORT_SHEET_PREFIX))
    .map(sh => ({
      name: sh.getName(),
      displayName: sh.getName().replace(IMPORT_SHEET_PREFIX, ''),
      rowCount: sh.getLastRow() - 1
    }));
}

function getColumnsForSheet(sheetName) {
  const sheet = SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(sheetName);
  if (!sheet) return [];
  return sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0].filter(Boolean);
}

function getAllColumns() {
  const sheets = getImportedSheets();
  const allCols = new Set();
  sheets.forEach(sh => getColumnsForSheet(sh.name).forEach(c => allCols.add(c)));
  return Array.from(allCols).sort();
}

// ==================== FILTER / SEARCH ====================
function getFilteredData(sheetName, filters) {
  const sheet = SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(sheetName);
  if (!sheet) return [];
  const data = sheet.getDataRange().getValues();
  if (data.length < 2) return [];
  const headers = data[0];
  let rows = data.slice(1).map(row => {
    const obj = {};
    headers.forEach((h, i) => obj[h] = row[i] || '');
    return obj;
  });

  if (filters.searchTerm) {
    const term = filters.searchTerm.toLowerCase();
    rows = rows.filter(r => Object.values(r).some(v => String(v).toLowerCase().includes(term)));
  }
  if (filters.column && filters.value) {
    rows = rows.filter(r => String(r[filters.column] || '').toLowerCase().includes(filters.value.toLowerCase()));
  }
  if (filters.dateField && (filters.dateFrom || filters.dateTo)) {
    rows = rows.filter(r => {
      const d = new Date(r[filters.dateField]);
      if (isNaN(d.getTime())) return false;
      if (filters.dateFrom && d < new Date(filters.dateFrom)) return false;
      if (filters.dateTo && d > new Date(filters.dateTo)) return false;
      return true;
    });
  }
  if (filters.class) rows = rows.filter(r => r.Class === filters.class);
  if (filters.section) rows = rows.filter(r => r.Section === filters.section);
  return rows;
}

function getGlobalSearchResults(filters) {
  const sheets = getImportedSheets();
  let all = [];
  sheets.forEach(sh => all = all.concat(getFilteredData(sh.name, filters)));
  return all;
}

function getPersonAllRecords(searchId) {
  const sheets = getImportedSheets();
  const results = {};
  sheets.forEach(sh => {
    const data = getFilteredData(sh.name, { searchTerm: searchId });
    if (data.length > 0) results[sh.displayName] = data;
  });
  return results;
}

function sendEmailReport(recipient, subject, htmlBody) {
  try {
    MailApp.sendEmail({ to: recipient, subject: subject, htmlBody: htmlBody });
    return { success: true };
  } catch(e) {
    return { success: false, message: e.toString() };
  }
}
